http:
  routers:
    django-router:
      rule: "Host(`app.localhost`) || Host(`localhost`)"
      entryPoints:
        - "websecure"
      service: "django-service"
      tls: {}

    livekit-router:
      rule: "Host(`livekit.localhost`)"
      entryPoints:
        - "websecure"
      service: "livekit-service"
      tls: {}

    centrifugo-router:
      rule: "Host(`centrifugo.localhost`)"
      entryPoints:
        - "websecure"
      service: "centrifugo-service"
      tls: {}

  services:
    django-service:
      loadBalancer:
        servers:
          - url: "http://django:8000"

    livekit-service:
      loadBalancer:
        servers:
          - url: "http://livekit:7880"

    centrifugo-service:
      loadBalancer:
        servers:
          - url: "http://centrifugo:8000"

tls:
  certificates:
    - certFile: /certs/local.crt
      keyFile: /certs/local.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/local.crt
        keyFile: /certs/local.key
