api:
  dashboard: false
  insecure: false

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "hostmaster@169.58.32.179.nip.io"
      storage: "/acme/acme.json"
      tlsChallenge: {}

providers:
  file:
    filename: "/etc/traefik/dynamic_conf.yml"
    watch: true
